name: CI/CD - DevOps App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: |
          cd app/backend
          npm install

      - name: Ejecutar pruebas
        run: |
          cd app/backend
          npm test

      - name: Construir imagen Docker
        run: |
          docker build -t devops-app .
